#! /bin/sh

### AUTOSTART ###
# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &
# Start blueman
blueman-applet &
# Set cursor
xsetroot -cursor_name left_ptr
# Set the resolution
${HOME}/.screenlayout/layout.sh
# Run compositor
picom -fb --experimental-backends &
# Restore the background
nitrogen --restore
# run polybar
sleep 5 & ${HOME}/.config/polybar/colorblocks/launch.sh
# run dunst
dunst &
# Run Battery checker
sh /opt/scripts/battery-status.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

#bspc config border_radius                8
bspc config border_width                  1
bspc config window_gap                    40
bspc config top_padding                   0
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

